title: Hannah Huihan Zhang
description: Ph.D. Student in Economics
author: Hannah Huihan Zhang
avatar: /photo.JPG
email: hhzhang@bu.edu
subscribe: false
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: huihan_zhang
  card: summary
logo: logo.png
social:
  name: Hannah Huihan Zhang
  links:
    - https://twitter.com/huihan_zhang
    - https://www.linkedin.com/in/huihan-hannah-zhang-a72531aa/
lang: en
