title: Hannah H. Zhang
description: Ph.D. Candidate in Economics at Boston University
author: Hannah H. Zhang
avatar: /logo.png
email: hhzhang@bu.edu

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: huihan_zhang
  card: summary
logo: logo.png
social:
  name: Hannah H. Zhang
  links:
    - https://twitter.com/huihan_zhang
    - https://www.linkedin.com/in/huihan-hannah-zhang-a72531aa/
lang: en
